
services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: always 
    ports:
      - "11434:11434"
    volumes:
      - /home/ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: always 
    ports:
      - "8080:8000"
    environment:
      - OLLAMA_BASE_URL=http://127.0.0.1:11434
    volumes:
      - open-webui:/app/backend/data
    network_mode: host

volumes:
  open-webui:
